[ci,fpga] Updated link for FPGA test reproducibility in CI workflow
When an FPGA job fails on CI the echo will now direct users to the
appropriate directions for reproducing locally.

Signed-off-by: Evan Apinis <eapinis@zerorisc.com>

diff --git a/.github/workflows/fpga.yml b/.github/workflows/fpga.yml
--- a/.github/workflows/fpga.yml
+++ b/.github/workflows/fpga.yml
@@ -106,7 +106,7 @@ jobs:
           # Run FPGA tests
           if [[ -s target_pattern_file.txt ]]; then
             ci/scripts/run-fpga-tests.sh "${{ inputs.interface }}" target_pattern_file.txt "$cache_test_results" ${{ inputs.extra_bazel_flags }} || {
-              res=$?; echo "To reproduce failures locally, follow the instructions at https://opentitan.org/book/doc/getting_started/setup_fpga.html#reproducing-fpga-ci-failures-locally"; exit "${res}";
+              res=$?; echo "To reproduce failures locally, follow the instructions at https://docs.pavona.org/book/doc/getting_started/setup_fpga.html#reproducing-fpga-ci-failures-locally"; exit "${res}";
             }
           else
             echo "No tests to run after filtering"
